#Plugins dành cho máy chủ folia
#Người phát triển: Lê Đạt

#sử dụng lệnh /DDCommand reload để làm mới tệp!
#sử dụng /discord hoặc /2y2cdiscord
discordLink: "https://discord.gg/3etJ94u3vj"

#sử dụng /napthe hoặc /donate
donateLink: "https://facebook.com/test hoặc H2#5850"
